import Head from 'next/head'
import Image from 'next/image'
import Home from "../src/views/home/home"
import styles from '../styles/Home.module.css'
import router from "next/router"

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
       
    </div>
  )
}
